services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:password@postgresql_host:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://postgresql_host:3000
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - database
    networks:
      - intranet

  database:
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      intranet:
        aliases:
          - postgresql_host

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      DB_USER: app_user
      DB_PASSWORD: password
      DB_HOST: postgresql_host
      DB_NAME: postgres
      POOL_MODE: session
      ADMIN_USERS: postgres,app_user
      AUTH_TYPE: scram-sha-256
      MAX_CLIENT_CONN: 1100
    ports:
      - 6432:5432
    depends_on:
      - database
    networks:
      intranet:
        aliases:
          - postgresql_pool

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      API_URL: http://127.0.0.1:3000/
    networks:
      - intranet

  db_console:
    image: adminer:4.8.1
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 8085:8080
    networks:
      - intranet

networks:
  intranet: