services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:password@postgresql_host:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://postgresql_host:3000
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - database
    networks:
      - intranet

  database:
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      intranet:
        aliases:
          - postgresql_host

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      API_URL: http://127.0.0.1:3000/
    networks:
      - intranet

  db_console:
    image: adminer:4.8.1
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 8085:8080
    networks:
      - intranet

networks:
  intranet: